package compiler

import (
	"bytes"
	"strings"
	"testing"
	"time"

	"github.com/pranavra0/ghaas/pkg/manifest"
	"gopkg.in/yaml.v3"
)

func TestCompileV01WorkflowIsDeterministicAndThin(t *testing.T) {
	fn := manifest.Function{
		Runtime: manifest.RuntimeCommand,
		Command: []string{"echo", "hello"},
		Timeout: manifest.Duration(90 * time.Second),
		Schedule: &manifest.ScheduleConfig{
			Cron:     "15 9 * * 5",
			Timezone: "America/New_York",
		},
		Environment: map[string]string{"ZED": "${{ vars.ZED }}", "A": "plain"},
		Secrets:     []string{"Z_SECRET", "A_SECRET"},
	}
	first, err := Compile("weekly", fn, Options{})
	if err != nil {
		t.Fatal(err)
	}
	second, err := Compile("weekly", fn, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first.Content, second.Content) {
		t.Fatal("compiler output is not deterministic")
	}
	if !bytes.HasPrefix(first.Content, []byte("# Code generated by ghaas. DO NOT EDIT.\n")) {
		t.Fatal("missing generated header")
	}
	if err := yaml.Unmarshal(first.Content, new(yaml.Node)); err != nil {
		t.Fatalf("generated workflow is not YAML: %v", err)
	}

	output := string(first.Content)
	for _, want := range []string{
		"name: 'ghaas: weekly'",
		"run-name: 'ghaas: weekly/${{ inputs.ghaas_invocation_id || github.run_id }}'",
		"cron: \"15 9 * * 5\"",
		"timezone: America/New_York",
		"workflow_dispatch:",
		"ghaas_invocation_id:",
		"contents: read",
		"timeout-minutes: 2",
		"uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683",
		`archive="ghaas-${version}-linux-${arch}.tar.gz"`,
		`base_url="https://github.com/pranavra0/ghaas/releases/download/${version}"`,
		`--output "$release_dir/SHA256SUMS"`,
		"sha256sum --check --status",
		`tar --extract --gzip --file "$release_dir/$archive" --directory "$install_dir"`,
		"run: ghaas runtime invoke weekly",
		"A: plain",
		"A_SECRET: \"${{ secrets.A_SECRET }}\"",
		"ZED: \"${{ vars.ZED }}\"",
		"Z_SECRET: \"${{ secrets.Z_SECRET }}\"",
		"GHAAS_FUNCTION: weekly",
		"GHAAS_INVOCATION_ID: \"${{ inputs.ghaas_invocation_id }}\"",
		"GHAAS_ATTEMPT: \"1\"",
		"GHAAS_TRIGGER: \"${{ github.event_name }}\"",
		"GHAAS_WORKFLOW_RUN_ID: \"${{ github.run_id }}\"",
	} {
		if !strings.Contains(output, want) {
			t.Errorf("generated workflow missing %q:\n%s", want, output)
		}
	}
	if strings.Index(output, "sha256sum --check --status") > strings.Index(output, "tar --extract --gzip") {
		t.Error("generated workflow extracts the release before verifying its checksum")
	}
	if strings.Contains(output, "go install") {
		t.Error("generated workflow requires a Go toolchain")
	}
	if strings.Contains(output, "./cmd/ghaas") {
		t.Error("generated workflow references local compiler source")
	}
	for _, forbidden := range []string{
		"issues: write", "contents: write", "GHAAS_STATE_", "GHAAS_RETRY_",
		"GHAAS_SLO_", "GHAAS_SCHEDULE_TARGET", "GHAAS_SCHEDULE_WINDOW",
		"on_exhausted", "dead-letter", "execution_window",
	} {
		if strings.Contains(output, forbidden) {
			t.Errorf("generated workflow contains v0.2 metadata %q", forbidden)
		}
	}
	if strings.Index(output, "A: plain") > strings.Index(output, "A_SECRET:") ||
		strings.Index(output, "A_SECRET:") > strings.Index(output, "GHAAS_ATTEMPT:") {
		t.Error("environment entries are not sorted")
	}
}

func TestCompileInstallerReleaseSetting(t *testing.T) {
	artifact, err := Compile("hello", manifest.Function{Runtime: manifest.RuntimeCommand, Command: []string{"echo"}}, Options{GhaasVersion: "v1.2.3"})
	if err != nil {
		t.Fatal(err)
	}
	output := string(artifact.Content)
	for _, want := range []string{
		`version="v1.2.3"`,
		`archive="ghaas-${version}-linux-${arch}.tar.gz"`,
		`https://github.com/pranavra0/ghaas/releases/download/${version}`,
		`--output "$release_dir/SHA256SUMS"`,
		"sha256sum --check --status",
	} {
		if !strings.Contains(output, want) {
			t.Fatalf("installer is missing %q:\n%s", want, output)
		}
	}
	if strings.Index(output, "sha256sum --check --status") > strings.Index(output, "tar --extract --gzip") {
		t.Fatal("installer extracts the release before verifying its checksum")
	}
	if strings.Contains(output, "go install") {
		t.Fatal("installer requires a Go toolchain")
	}
	if strings.Contains(output, "./cmd/ghaas") {
		t.Fatal("installer assumes ghaas source in target repository")
	}
}

func TestCompileRejectsUnsafeReleaseVersion(t *testing.T) {
	for _, version := range []string{"v1.2.3; echo compromised", "v1.2.3\nGITHUB_TOKEN=leak", "v01.2.3", "1.2.3"} {
		if _, err := Compile("hello", manifest.Function{Runtime: manifest.RuntimeCommand, Command: []string{"echo"}}, Options{GhaasVersion: version}); err == nil {
			t.Fatalf("unsafe release version %q was accepted", version)
		}
	}
}

func TestCompileRejectsEnvSecretCollisionsAndReservedNames(t *testing.T) {
	cases := []manifest.Function{
		{Environment: map[string]string{"TOKEN": "plain"}, Secrets: []string{"TOKEN"}},
		{Environment: map[string]string{"GHAAS_CUSTOM": "shadow"}},
		{Secrets: []string{"GHAAS_CUSTOM"}},
	}
	for _, fn := range cases {
		if _, err := Compile("hello", fn, Options{}); err == nil {
			t.Fatal("expected invalid env/secrets configuration to be rejected")
		}
	}
}

func TestCompileAllSortsConcreteManifestNamesAndInheritsTimeout(t *testing.T) {
	all, err := CompileAll(manifest.Manifest{
		Version:  1,
		Defaults: manifest.Defaults{Timeout: manifest.Duration(3 * time.Minute)},
		Functions: map[string]manifest.Function{
			"z": {Runtime: manifest.RuntimeCommand, Command: []string{"echo", "z"}},
			"a": {Runtime: manifest.RuntimeCommand, Command: []string{"echo", "a"}},
		},
	}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if len(all) != 2 || all[0].Name != "a" || all[1].Name != "z" {
		t.Fatalf("unexpected order: %#v", all)
	}
	if !strings.Contains(string(all[0].Content), "timeout-minutes: 3") {
		t.Fatal("manifest default timeout was not inherited")
	}
}
