package compiler

import (
	"bytes"
	"testing"

	"gopkg.in/yaml.v3"
)

type testSchedule struct{ Cron, Timezone string }
type testFunction struct {
	Timeout     int64
	Schedule    *testSchedule
	Environment map[string]string
	Secrets     []string
}
type testManifest struct{ Functions map[string]testFunction }

func TestCompileIsDeterministicAndStructured(t *testing.T) {
	fn := testFunction{Timeout: 90 * 1e9, Schedule: &testSchedule{Cron: "15 9 * * 5", Timezone: "America/New_York"}, Environment: map[string]string{"ZED": "${{ vars.ZED }}", "A": "plain"}, Secrets: []string{"Z_SECRET", "A_SECRET"}}
	opts := Options{GhaasInstall: "go install example.invalid/ghaas@v1.2.3"}
	first, err := Compile("weekly", fn, opts)
	if err != nil {
		t.Fatal(err)
	}
	second, err := Compile("weekly", fn, opts)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first.Content, second.Content) {
		t.Fatal("compiler output is not deterministic")
	}
	if !bytes.HasPrefix(first.Content, []byte("# Code generated by ghaas. DO NOT EDIT.\n")) {
		t.Fatal("missing generated header")
	}
	var document map[string]any
	if err := yaml.Unmarshal(first.Content, &document); err != nil {
		t.Fatal(err)
	}
	if document["name"] != "ghaas: weekly" {
		t.Fatalf("unexpected name: %#v", document["name"])
	}
	triggers, ok := document["on"].(map[string]any)
	if !ok {
		t.Fatalf("on is not a mapping: %#v", document["on"])
	}
	if _, ok := triggers["schedule"]; !ok {
		t.Fatal("schedule missing")
	}
	if _, ok := triggers["workflow_dispatch"]; !ok {
		t.Fatal("workflow_dispatch missing")
	}
	jobs := document["jobs"].(map[string]any)
	invoke := jobs["invoke"].(map[string]any)
	if invoke["timeout-minutes"] != 2 {
		t.Fatalf("timeout did not round up: %#v", invoke["timeout-minutes"])
	}
	env := invoke["steps"].([]any)[2].(map[string]any)["env"].(map[string]any)
	if env["ZED"] != "${{ vars.ZED }}" || env["A_SECRET"] != "${{ secrets.A_SECRET }}" {
		t.Fatalf("expressions were not preserved: %#v", env)
	}
	for _, pair := range []string{"A:", "A_SECRET:", "GHAAS_FUNCTION:", "ZED:", "Z_SECRET:"} {
		if !bytes.Contains(first.Content, []byte(pair)) {
			t.Fatalf("missing env entry %s", pair)
		}
	}
	if bytes.Index(first.Content, []byte("A:")) > bytes.Index(first.Content, []byte("A_SECRET:")) || bytes.Index(first.Content, []byte("A_SECRET:")) > bytes.Index(first.Content, []byte("GHAAS_FUNCTION:")) {
		t.Fatal("environment entries are not sorted")
	}
}

func TestCompileAllSortsNames(t *testing.T) {
	all, err := CompileAll(testManifest{Functions: map[string]testFunction{"z": {}, "a": {}}}, Options{GhaasInstall: "install"})
	if err != nil {
		t.Fatal(err)
	}
	if len(all) != 2 || all[0].Name != "a" || all[1].Name != "z" {
		t.Fatalf("unexpected order: %#v", all)
	}
}
