package compiler

import (
	"fmt"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const defaultGhaasInstall = "go run ./cmd/ghaas"

type workflow struct{ root yaml.Node }

func buildWorkflow(name string, function any, options Options) (workflow, error) {
	v := indirect(reflect.ValueOf(function))
	if !v.IsValid() {
		return workflow{}, fmt.Errorf("function %q is nil", name)
	}

	install := options.GhaasInstall
	if install == "" {
		install = options.InstallCommand
	}
	if install == "" {
		install = options.Install
	}
	if install == "" {
		install = options.GhaasInstallCommand
	}
	if install == "" {
		install = options.InstallURL
	}
	if install == "" && options.GhaasVersion != "" {
		install = "go install ghaas/cmd/ghaas@" + options.GhaasVersion
	}
	if install == "" {
		install = defaultGhaasInstall
	}

	root := yaml.Node{Kind: yaml.MappingNode}
	addPair(&root, scalar("name"), scalar("ghaas: "+name))

	on := yaml.Node{Kind: yaml.MappingNode}
	if schedule := indirect(field(v, "Schedule")); schedule.IsValid() {
		cron := stringField(schedule, "Cron")
		if cron != "" {
			schedules := yaml.Node{Kind: yaml.SequenceNode}
			entry := yaml.Node{Kind: yaml.MappingNode}
			cronNode := scalarQuoted(cron)
			if timezone := stringField(schedule, "Timezone"); timezone != "" {
				cronNode.LineComment = "timezone: " + timezone
			}
			addPair(&entry, scalar("cron"), cronNode)
			schedules.Content = append(schedules.Content, &entry)
			addPair(&on, scalar("schedule"), &schedules)
		}
	}
	// The optional input gives manual dispatches a stable UUID. Scheduled
	// dispatches leave it empty and derive their key in the runtime.
	dispatch := yaml.Node{Kind: yaml.MappingNode}
	inputs := yaml.Node{Kind: yaml.MappingNode}
	input := yaml.Node{Kind: yaml.MappingNode}
	addPair(&input, scalar("description"), scalar("ghaas logical invocation UUID"))
	addPair(&input, scalar("required"), scalarBool(false))
	addPair(&input, scalar("type"), scalar("string"))
	addPair(&inputs, scalar("ghaas_invocation_id"), &input)
	addPair(&dispatch, scalar("inputs"), &inputs)
	addPair(&on, scalar("workflow_dispatch"), &dispatch)
	addPair(&root, scalar("on"), &on)

	permissions := yaml.Node{Kind: yaml.MappingNode}
	addPair(&permissions, scalar("contents"), scalar("write"))
	addPair(&root, scalar("permissions"), &permissions)

	concurrency := yaml.Node{Kind: yaml.MappingNode}
	addPair(&concurrency, scalar("group"), scalar("ghaas-"+name))
	addPair(&concurrency, scalar("cancel-in-progress"), scalarBool(false))
	addPair(&root, scalar("concurrency"), &concurrency)

	job := yaml.Node{Kind: yaml.MappingNode}
	addPair(&job, scalar("runs-on"), scalar("ubuntu-latest"))
	minutes, err := timeoutMinutes(v, options.DefaultTimeoutValue())
	if err != nil {
		return workflow{}, fmt.Errorf("function %q timeout: %w", name, err)
	}
	addPair(&job, scalar("timeout-minutes"), scalarInt(minutes))

	steps := yaml.Node{Kind: yaml.SequenceNode}
	checkout := yaml.Node{Kind: yaml.MappingNode}
	addPair(&checkout, scalar("uses"), scalar("actions/checkout@v4"))
	steps.Content = append(steps.Content, &checkout)

	installStep := yaml.Node{Kind: yaml.MappingNode}
	addPair(&installStep, scalar("name"), scalar("Install ghaas"))
	addPair(&installStep, scalar("run"), scalar(install))
	steps.Content = append(steps.Content, &installStep)

	invoke := yaml.Node{Kind: yaml.MappingNode}
	addPair(&invoke, scalar("name"), scalar("Invoke function"))
	env := environment(v)
	env["GHAAS_FUNCTION"] = name
	env["GHAAS_INVOCATION_ID"] = "${{ inputs.ghaas_invocation_id }}"
	env["GHAAS_ATTEMPT"] = "1"
	env["GHAAS_TRIGGER"] = "${{ github.event_name }}"
	env["GHAAS_WORKFLOW_RUN_ID"] = "${{ github.run_id }}"
	secretNames := secretValues(v)
	sort.Strings(secretNames)
	for _, key := range secretNames {
		if _, exists := env[key]; !exists {
			env[key] = "${{ secrets." + key + " }}"
		}
	}
	envNode := yaml.Node{Kind: yaml.MappingNode}
	envKeys := make([]string, 0, len(env))
	for key := range env {
		envKeys = append(envKeys, key)
	}
	sort.Strings(envKeys)
	for _, key := range envKeys {
		addPair(&envNode, scalar(key), scalarPreserving(env[key]))
	}
	addPair(&invoke, scalar("env"), &envNode)
	addPair(&invoke, scalar("run"), scalar("ghaas runtime invoke "+name))
	steps.Content = append(steps.Content, &invoke)
	addPair(&job, scalar("steps"), &steps)

	jobs := yaml.Node{Kind: yaml.MappingNode}
	addPair(&jobs, scalar("invoke"), &job)
	addPair(&root, scalar("jobs"), &jobs)
	return workflow{root: root}, nil
}

func renderWorkflow(w workflow) ([]byte, error) {
	content, err := yaml.Marshal(&w.root)
	if err != nil {
		return nil, err
	}
	return append([]byte("# Code generated by ghaas. DO NOT EDIT.\n"), content...), nil
}

func addPair(mapping *yaml.Node, key, value *yaml.Node) {
	mapping.Content = append(mapping.Content, key, value)
}
func scalar(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
}
func scalarInt(value int) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: strconv.Itoa(value)}
}
func scalarBool(value bool) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: strconv.FormatBool(value)}
}
func scalarQuoted(value string) *yaml.Node {
	n := scalar(value)
	n.Style = yaml.DoubleQuotedStyle
	return n
}
func scalarPreserving(value string) *yaml.Node {
	// Expressions are plain data, never shell fragments. Double-quoting only
	// affects YAML syntax and leaves the expression value byte-for-byte intact.
	if strings.HasPrefix(value, "${{") && strings.HasSuffix(value, "}}") {
		return scalarQuoted(value)
	}
	return scalar(value)
}

func stringField(v reflect.Value, name string) string {
	return stringValue(field(v, name))
}
func stringValue(v reflect.Value) string {
	v = indirect(v)
	if !v.IsValid() {
		return ""
	}
	if v.Kind() == reflect.String {
		return v.String()
	}
	if v.CanInterface() {
		if s, ok := v.Interface().(fmt.Stringer); ok {
			return s.String()
		}
	}
	return ""
}

func timeoutMinutes(v reflect.Value, fallback time.Duration) (int, error) {
	value := indirect(field(v, "Timeout"))
	if !value.IsValid() {
		return durationMinutes(fallback), nil
	}
	duration, err := durationValue(value)
	if err != nil {
		return 0, err
	}
	if duration <= 0 {
		return durationMinutes(fallback), nil
	}
	return durationMinutes(duration), nil
}

func durationMinutes(duration time.Duration) int {
	if duration <= 0 {
		duration = 15 * time.Minute
	}
	minutes := int(duration / time.Minute)
	if duration%time.Minute != 0 {
		minutes++
	}
	if minutes < 1 {
		minutes = 1
	}
	return minutes
}

func durationValue(value reflect.Value) (time.Duration, error) {
	value = indirect(value)
	if !value.IsValid() {
		return 0, nil
	}
	switch value.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return time.Duration(value.Int()), nil
	case reflect.String:
		if value.String() == "" {
			return 0, nil
		}
		return time.ParseDuration(value.String())
	case reflect.Struct:
		return durationValue(field(value, "Duration"))
	default:
		return 0, fmt.Errorf("unsupported duration type %s", value.Type())
	}
}
func durationFromReflect(v reflect.Value) time.Duration {
	d, _ := durationValue(v)
	return d
}

func environment(v reflect.Value) map[string]string {
	for _, name := range []string{"Environment", "Env"} {
		m := indirect(field(v, name))
		if !m.IsValid() || m.Kind() != reflect.Map {
			continue
		}
		out := make(map[string]string, m.Len())
		for _, key := range m.MapKeys() {
			out[stringValue(key)] = stringValue(m.MapIndex(key))
		}
		return out
	}
	return map[string]string{}
}
func secretValues(v reflect.Value) []string {
	values := indirect(field(v, "Secrets"))
	if !values.IsValid() || (values.Kind() != reflect.Slice && values.Kind() != reflect.Array) {
		return nil
	}
	out := make([]string, 0, values.Len())
	for i := 0; i < values.Len(); i++ {
		if name := stringValue(values.Index(i)); name != "" {
			out = append(out, name)
		}
	}
	return out
}
